### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by belokonm** [samedii/fullcalendar#3]
Hello. Can you give any example hot to use your view? I did repo and add link to <link href="/assets/plugins/fc/dist/fullcalendar.css" rel="stylesheet" />

<script src="/assets/plugins/fc/dist/fullcalendar.js"></script>

Then I did configuration as
header: {
                    left: 'title',
                    center: '',
                    right: 'prev,month,basicWeek,agendaFourDay,basicList,next'
                },
But I can't see any new button.
Thx.

**Comment by belokonm** [comment]
Found. 
I need to add 'list' instead of 'basicList'

**Comment by samedii** [comment]
@belokonm You should try using the new system for adding plugins instead. I just posted how I did it here: [Fullcalendar google issues tracker](https://code.google.com/p/fullcalendar/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Milestone%20Summary%20Stars&groupby=&sort=&id=289)
